name: Generate News Sitemap

on:
  schedule:
    - cron: '0 12 * * *' # Every day at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # 🔐 Allows pushing back to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Generate news sitemap
        run: node fetch-webflow-news.js
        env:
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add news-sitemap.xml
          git commit -m "Update sitemap" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
